{
    'name': 'Fleet - Múltiples Matrículas',
    'version': '19.0.1.0.0',
    'summary': 'Permite registrar hasta 3 matrículas por vehículo',
    'category': 'Fleet',
    'author': 'Alphaqueb Consulting SAS',
    'depends': ['fleet', 'service_order'],
    'data': [
        'security/ir.model.access.csv',
        'data/fleet_safety_equipment_cron.xml',
        'views/fleet_vehicle_views.xml',
        'views/fleet_driver_commission_views.xml',
        'views/service_order_commission_report_views.xml',
        'views/fleet_driver_commission_menus.xml',
        'views/fleet_safety_equipment_views.xml',
    ],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
